# config/routes.yaml ou dans un fichier spécifique sous config/routes/

# Configuration automatique des routes via les attributs dans les contrôleurs
controllers:
    resource: '../src/Controller/'
    type: attribute

# Définition explicite de la route 'update_budget'
update_budget:
    path: '/profile/update-budget/{id}'
    controller: App\Controller\ProfileController::updateBudget
    methods: [POST]


index:
    path: /{_locale}/
    controller: App\Controller\MainController::index
    requirements:
        _locale: 'en|fr'
    defaults:
        _locale: 'en'

# config/routes.yaml
contact:
    path: /contact
    controller: App\Controller\ContactController::contact
    methods: ['GET', 'POST']

# config/routes.yaml

confirmation:
    path: /confirmation
    controller: App\Controller\ContactController::confirmation
about:
    path: /about
    controller: App\Controller\AboutController::index
