# config/routes.yaml ou dans un fichier spécifique sous config/routes/

# Configuration automatique des routes via les attributs dans les contrôleurs
controllers:
    resource: '../src/Controller/'
    type: attribute

# Définition explicite de la route 'update_budget'
update_budget:
    path: '/profile/update-budget/{id}'
    controller: App\Controller\ProfileController::updateBudget
    methods: [POST]


index:
    path: /{_locale}/
    controller: App\Controller\MainController::index
    requirements:
        _locale: 'en|fr'
    defaults:
        _locale: 'en'